Add timeout and elapsed time

diff --git a/analyze b/analyze
--- a/analyze
+++ b/analyze
@@ -32,17 +32,21 @@ then
     exit 1
 fi
 
-java_file="$1"
 shift 1
-if [ ! -f "$java_file" ]
+if [ ! -f "$src_file" ]
 then
-    echo "Could not find file: $java_file"
+    echo "Could not find file: $src_file"
     exit 1
 fi
 
+problem="$(basename $(dirname $(dirname $src_file)))"
+solution="$(basename ${src_file%.java})"
+[ "$verbose" == "1" ] && echo "problem=$problem solution=$solution"
+run_id="java_${problem}_${solution}"
+
 # Create temp dir, copy solution file to it, compile
 tmpdir="$(mktemp -d)"
-cp "$java_file" "$tmpdir/Main.java"
+cp "$src_file" "$tmpdir/Main.java"
 cd "$tmpdir"
 [ "$verbose" == "1" ] && echo "Compiling..."
 javac -encoding utf8 -g Main.java # Fix for compiling Japanese code https://stackoverflow.com/a/14672757/8999671
@@ -55,10 +59,6 @@ fi
 # Infer output and trace files
 if [ ! -z "$infer_output_files" ]
 then
-    problem="$(basename $(dirname $(dirname $src_file)))"
-    solution="$(basename ${src_file%.java})"
-    [ "$verbose" == "1" ] && echo "problem=$problem solution=$solution"
-    run_id="java_${problem}_${solution}"
     trace_arg="-l $starting_cwd/logs/$run_id.xml"
     output_arg="-o $starting_cwd/outputs/$run_id.txt"
     mkdir -p "$starting_cwd/logs" "$starting_cwd/outputs"
@@ -66,7 +66,16 @@ fi
 
 [ "$verbose" == "1" ] && verbose_arg="-v"
 [ "$verbose" == "1" ] && (echo "Analyzing..."; echo "command=$app_exe Main main $trace_arg $output_arg")
-"$app_exe" Main main $trace_arg $output_arg $verbose_arg < $input_file
+
+start="$(date +%s)"
+[ "$verbose" == "1" ] && echo "$run_id begin: $start"
+timeout 10s "$app_exe" Main main $trace_arg $output_arg $verbose_arg < $input_file
+exit_code="$?"
+end="$(date +%s)"
+elapsed="$(echo "$end - $start" | bc)"
+[ "$verbose" == "1" ] && (echo  "$run_id end: $end"; echo "$run_id elapsed seconds: $elapsed")
+[ "$verbose" == "1" ] && echo "$run_id exit code: $exit_code"
+
 exitCode="$?"
 rm -r $tmpdir
 
